# Generated by Django 5.2.3 on 2025-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(verbose_name='max_length = 200'),
        ),
    ]
