# Generated by Django 5.2.3 on 2025-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
        migrations.AddField(
            model_name='author',
            name='password_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
    ]
